security:
    # enable_authenticator_manager: true
    password_hashers:
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost:      15
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/api
            stateless: true
            jwt: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            json_login:
                check_path: /api/login_check # The route the SPA will POST to
                username_path: username      # Key in the JSON payload for the username
                password_path: password      # Key in the JSON payload for the         
                # success_handler: App\Security\LoginFormAuthenticator.onAuthenticationSuccess
                # failure_handler: App\Security\LoginFormAuthenticator.onAuthenticationFailure
            logout:
                path: app_logout
                target: app_home 

            lazy: true
            provider: app_user_provider

            # two_factor:
            #     auth_form_path: 2fa_login
            #     check_path: 2fa_login_check

    access_control:
        - { path: ^/, roles: PUBLIC_ACCESS  }
        - { path: ^/api/register, roles: PUBLIC_ACCESS  }
        - { path: ^/api/login, roles: PUBLIC_ACCESS  }
        - { path: ^/api/addproduct, roles: PUBLIC_ACCESS  }
        - { path: ^/api/productlist, roles: PUBLIC_ACCESS  }
        - { path: ^/productlistings, roles: PUBLIC_ACCESS  }

        - { path: ^/api/productsearch, roles: PUBLIC_ACCESS  }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
                
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
