# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    App\EventListener\JWTInvalidListener:
            tags: ['kernel.event_subscriber']

    App\Controller\UserController:
        # if your controller is not autowired by default
        # or if you want to be explicit
        autowire: true
        public: true # adjust visibility as needed
        arguments:
            # Explicitly alias the interface to the concrete service provided by the bundle
            '$totpAuthenticator': '@scheb_two_factor.security.totp_authenticator'

    Scheb\TwoFactorBundle\Security\TwoFactor\Provider\TwoFactorProviderRegistry: '@scheb_two_factor.provider_registry'



    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
